### PR TITLE
Using stateline as external dependency

### PR DESCRIPTION
**Pull request by dtpc**
Here are some changes I had to make to get stateline working as a dependency for obsidian.

The main ones are the last 3

1. I had to make it a shared library in order to link against it from an externally project.
2. Forward the minion address to the delegator. Is the delegator supposed to know about minions or only workers? If only workers, how does a job of type A reach the correct minion who supports only A? It seems there would either need to be a worker per job type, or every minion needs to support all job types.
3. Add a queue (and minionWaiting flag) per minion in the worker. Without this only one job would be executed at a time for each worker, regardless of how many minions are connected.

There are a couple of other issues, but I want to check first if I am using stateline correctly or if I have made some wrong assumptions.

### CODE REVIEW

**Comment by darrnshn** [comment]
Thanks for the contribution! I'm interested to know how easy it was to link against stateline using a shared library. Did you have to link with stateline's dependencies as well (e.g. zmq, json, glog)?

In the move-app-workers branch, I'm building stateline as one static library containing all its dependencies to simplify linking (especially if one is not using CMake). However, I don't know if that's possible with shared libraries. Perhaps a flag that lets you choose between the two would be good?

As for the minion/worker issues, the communications system in stateline is different to obsidian. My understanding is that, in stateline, workers and minions have a one-to-one correspondence, whereas in obsidian, multiple minions can connect to a worker. So a minion in obsidian is a worker-minion pair in stateline.

For example, in obsidian, you would have a minion for each job type. If you're using stateline, you would either:
a) Launch a worker-minion pair for each job type (preferred).
b) Launch a single worker-minion pair that takes all jobs, then manually launch threads to do each job type as they come along.

So I think the original code is correct, sorry for the confusion. We should probably have some documentation on this.

**Comment by dtpc** [comment]
I have obsidian already linking against the stateline's dependencies, as they are (were) all required by obsidian also. The static statelineclient/statelineserver libs were being linked to other libs in stateline, which works fine in the one cmake project, but not when linking from another project. The changes you're making may fix this.  

Is there a reason for the change to a 1-1 worker-minion mapping? My understanding was that the worker was to be generic and always cpp, and that minions could be created in any language. Currently the worker socket address is hard-coded as "ipc:///tmp/sl_worker.socket", meaning that there can only be 1 minion and 1 worker per machine, is this correct? If that's so, then I guess I should be looking at option (b) you mentioned above.

**Comment by dtpc** [comment]
The worker wrapper has a "nThreads" variable indicating the number of minion threads to run for the 1 worker. I think this confused me also. Even if they must all be the same jobtype, some change is required to the worker "queue/minionWaiting" code, otherwise only one of the minions will be used.

**Comment by darrnshn** [comment]
Yes, you're right! There is a problem here...my understanding is that there's a 1-1 relationship, so having the `nThreads` variable there is a bit strange. I'm not that familiar with the comms system, so I think it's best to wait till @lmccalman has seen this.

**Comment by lmccalman** [comment]
Yeah, the nthreads is a mistake, I should never have put it in to the worker wrapper.... my preference is to go 1-1 with minion-worker, beause it simplifies both the worker and the minion, and there overhead of a worker is pretty low (just heartbeating really). It should already be working like that in stateline I think, and if I recall correctly the minion specifies which jobs it is able to do?

**Comment by darrnshn** [comment]
The minion should be able to specify the job types it wants to do.

So I guess the two options are:
a) Randomly generate addresses for worker-minion pairs, so you can run multiple instances on the same machine
b) Have just one worker-minion pair, and the burden is on the minion to handle the different job types in separate threads (this is probably the better method)

With b), I think it's safe to do something like:
1) receive a job
2) launch new thread to handle job
3) repeat

The delegator should have mechanisms to prevent throttling the worker with too much work.

**Comment by lmccalman** [comment]
We're already doing a) =)
The thing about b) is that you basically end up re-writing the delegator locally! The minion blocking is probably the functionality we want, and as you say darren, have the smarts in the delegator making sure they don't send too many jobs to that worker (we do this currently I think by keeping track of haw many jobs are in each worker's local queue).

**Comment by darrnshn** [comment]
Ah right my mistake, forgot that you can have multiple things on the same IPC channel. Yeah B's a bad idea =P

**Comment by lmccalman** [comment]
Sounds like we've converged on a decent solution (Dave and I have also been chatting in slack), so as far as I'm concerned, Dave -- just push when you're ready. Darren -- thanks for looking over the code, and good luck with your exams!!!!!

**Comment by darrnshn** [comment]
Awesome, thanks for the help!! @dtpc you can push the shared library/local install changes, it might be a while before I can get the static lib changes merged in.

**Comment by dtpc** [comment]
Ok, I will push those library/cmake changes. Are there any other cpp projects which are linking against stateline? 

Also, how does the multiple minion-worker pairs using the same IPC socket address work?

**Comment by darrnshn** [comment]
I don't know of any other libraries linking against stateline.

For the sharing the same IPC socket...I'm not exactly sure. It doesn't seem to give an error or anything if multiple processes bind to the same address. But it does seem a bit weird, how does the processes know what messages are for them? If it's a problem, then we'll have to dynamic generate the socket address (it's a file after all).

**Comment by dtpc** [comment]
I have been playing around with multiple minion-worker pairs today, and it does give an error. Sometimes  'socket in use', sometimes the minion connects to the wrong worker. I've added some code to generate a random address in the workerwrapper class and pass it to the minion and worker constructors.

**Comment by darrnshn** [comment]
Awesome! Sounds good. You can push it to this pull request if you want, and I can have a look.

**Comment by dtpc** [comment]
I just realised that we probably want to be able specify it in config also, for users who run workers and minions as separate processes. So I will add this in also first.

**Comment by dtpc** [comment]
I removed the commits about trying to connect multiple minions to 1 worker and added 2 more:

3f6f407 Removed `nthreads` option and made minion-workers 1-1. A minion supports multiple job types by passing it a map of jobtypes -> likelihood functions. 

84d62a3 Worker ipc socket address is part of WorkerSettings. When using WorkerWrapper to create a worker-minion pair, this address is randomly generated.

**Comment by darrnshn** [comment]
Looks good! I like the new `WorkerWrapper` constructor with the likelihood map. Do you think it would be worth keeping the old `WorkerWrapper` constructor that takes a single likelihood function? There's two situations where I think it could be more convenient to give just one likelihood function:

1. If the user doesn't use job types (for very simple MCMCs)
2. The likelihood functions are very similar, possibly differing only by some constants that is determined by the job type. It would be good to just specify a generic likelihood function and allow the user to manually pick between different implementations.

What do you think? Other than that, it looks good to be merged!

**Comment by dtpc** [comment]
Yes, good point, I didn't think of that!

I've added a new commit providing the original functionality, i.e. construct `WorkerWrapper` with a single `LikelihoodFn` and a vector of job types. There is also a 3rd contructor, which takes a function which will return a `LikelihoodFn` given a job type string, which can be used to provide any type of mapping in case the first 2 options don't fit. Let me know if you think this is too much!

**Comment by dtpc** [comment]
Just hold off on looking at that, while it seems to work fine in the stateline demo, there's something not right with obsidian, when using it. I think it's losing a reference captured in the original likelihood function lambda.

**Comment by dtpc** [comment]
Ok that's fixed now. The problem was the lambda returning by value by default.

**Comment by darrnshn** [comment]
Yeah, looks good! That third constructor is probably overkill, but I don't see any harm in adding it in. Can I merge this in now?

**Comment by dtpc** [comment]
Yep, good to merge.

**Pull request merged**
