### PR TITLE
Move some dependencies to external

### PR DESCRIPTION
**Pull request by darrnshn**
This patch moves single header file dependencies to an external folder instead of downloading it from the web.

- Simplifies the fetch-deps script
- Ensure that all stateline builds are from the same versions of those dependencies
- Reduces build time

See #63.

### CODE REVIEW

**Comment by darrnshn** [comment]
@AlistaiReid This change shouldn't affect any of your cluster/docker stuff right? As long as dependencies are built using fetch-deps, everything should be good. I'm just double checking with you before this gets merged.

**Comment by AlistaiReid** [comment]
Shouldn't, but I'd still run docker build just in case. Looks like travis is unhappy, whats that about...

Actually, i was thinking of moving to a 2 stage docker build - fetch-deps takes about 20 minutes, while compiling stateline takes about 2 minutes, so im tempted to have a stateline-env dockerfile, and a stateline dockerfile based off it - what do you think?

**Comment by darrnshn** [comment]
Having the two stage build sounds good. I don't know much about docker, so what would be the downside to having the two stage build?

Louis is still working on the travis stuff, so until that gets merged to master all the pull request will fail because not all branches have a .travis.yml yet. Once he merges it in, I'll rebase the pull requests to get the travis config file and it should theoretically work.

**Comment by ltiao** [comment]
There's aren't really any downsides other than having an additional Dockerfile to maintain. I think should actually try to make Docker cache a little smarter, but the caching rules can become pretty complex. This may be helpful: http://kimh.github.io/blog/en/docker/gotchas-in-writing-dockerfile-en/#build_caching_what_invalids_cache_and_not.

I think we're good to just merge in the branch with the `.travis.yml` file. There isn't much else that needs to be done with it to make the builds pass. Everything really comes to cleaning up the Docker build process a bit.

**Comment by AlistaiReid** [comment]
Docker builds on this commit.

**Comment by darrnshn** [comment]
Thanks Al

**Pull request merged**
